Dashboard
Rale13/playwright pull request #15
Opened 2024-10-10 09:51 UTC by Rale13

2024-10-10 13:02 UTC, filip-n91 requested changes

2024-10-10 13:02 UTC, filip-n91 commented on pom/modules/ui/dashboard.js
> +    this.gearLocator = page.locator("[src='/images/logo/-white.png']");
Ovo je pre deo Header POM-a

2024-10-10 13:02 UTC, filip-n91 commented on pom/modules/ui/dashboard.js
> +export const switchBetweenPages = async (page, dashboard, pageBtn) => {
Sve ove funkcije bi trebale da su unutar klase

2024-10-10 13:02 UTC, filip-n91 commented on tests/home/dashboard.spec.js
> +  test("gear icon should be visible", async () => {
Nepotreban test za dashboard, ikonica je uvek prisutna u headeru na kojoj god stranici bili

2024-10-11 08:01 UTC, filip-n91 commented on pom/modules/ui/dashboard.js
> +export const collectAllProductsData = async (page, dashboard) => {
Jesi ovo zaboravio da izbrises?

2024-10-11 08:06 UTC, Rale13 commented on pom/modules/ui/dashboard.js
> +export const collectAllProductsData = async (page, dashboard) => {
jesam, ispravio sam

2024-10-11 12:34 UTC, merged